_target_: olympus_core.core.ModuleDatasets    
train:
  _target_: torch.utils.data.ConcatDataset
  _partial_: True
  datasets:
    - _target_: src.datasets.imagenet_dataset.ImageNetKaggle
      root: "${mounts.external}/ImageData/ImageNet"
      pretraining: False
test:
  - _target_: src.datasets.imagenet_dataset.ImageNetKaggle
    _partial_: True
    root: "${mounts.external}/ImageData/ImageNet"
    split: "val"
    pretraining: False