_target_: olympus_core.core.ModuleDatasets    
train:
  _target_: torch.utils.data.ConcatDataset
  _partial_: True
  datasets:
    - _target_: src.datasets.classification_dataset.ClassificationDataset
      root: "${mounts.external}/ImageData"
      name: Places365
      crop_scale: 0.36
      split: "train"
      pretraining: True
      resolution: 224
test:
  - _target_: src.datasets.classification_dataset.ClassificationDataset
    _partial_: True
    root: "${mounts.external}/ImageData"
    name: Places365
    split: "test"
    pretraining: True
    resolution: 224