defaults:
  - datasets/ade20k@datasets: ade20k_dataset
  - dataloaders: default_dataloader
  - _self_
_target_: olympus_core.core.OlympusDataModule
split_train_validate: False
validate_split_ratio: 0.1
