defaults:
  - datasets/segmentation@datasets: segmentation_dataset
  - dataloaders: default_dataloader
  - _self_
_target_: olympus_core.core.OlympusDataModule
split_train_validate: False
validate_split_ratio: 0.1
